### ISSUE TITLE
Split prompt by line broken?

### ISSUE THREAD

**Issue by slack-t** [rsxdalv/tts-generation-webui#163]
Hi,
It seems like since the last update the 'Split prompt by line' option on Bark TTS is broken. It results in generations of the content e.g. "Empty History" per line. 
I usually use Linux but installed everything on windows again and the issue is reproducible.
Thanks 🙏

**Comment by bkutasi** [comment]
Hi, same happened to me. Also spun up a container to verify it.

**Comment by Maki9009** [comment]
i think all of bark is broken for me..

**Comment by rsxdalv** [comment]
Thanks for the report, I'll check how to fix it. In the meantime,
downgrading can be done by checking out an older commit. (From the
tts-generation-webui folder).

**Comment by rsxdalv** [comment]
I found the issue, fixed in the latest update.

**Comment by bkutasi** [comment]
At the moment, It's still broken for me. Anybody still has the same issue? Maybe something went wrong on my side.

**Comment by rsxdalv** [comment]
> At the moment, It's still broken for me. Anybody still has the same issue? Maybe something went wrong on my side.

Are you seeing that same problem?

**Comment by bkutasi** [comment]
Hey, sorry for the delay. I did with a local venv test and its working! I guess i will stop using docker for a while, until i figure out what went wrong. I will post it here if i find something but if not feel free to close it.

**Comment by rsxdalv** [comment]
Perhaps it just needs to be rebuilt. Docker itself ought to work the
same way.
